### ISSUE TITLE
Fresh install of semantic-ui-ember fails bc of missing bowerrc (and then some)

### ISSUE THREAD

**Issue by allthesignals** [Semantic-Org/Semantic-UI-Ember#192]
```
ember-cli: 2.13.0
node: 7.7.4
os: darwin x64
```

New `ember-cli` no longer includes bowerrc: https://github.com/ember-cli/ember-cli/releases/tag/v2.13.0-beta.4. 

Related discussion: #188 

This may throw some people off. Making the bowerrc file is fine, but then:

```
[BABEL] Note: The code generator has deoptimised the styling of "default-package/bower_components/semantic-ui/dist/semantic.js" as it exceeds the max of "500KB".
File: default-package/bower_components/semantic-ui/gulpfile.js
The Broccoli Plugin: [broccoli-persistent-filter:Babel] failed with:
TypeError: default-package/bower_components/semantic-ui/gulpfile.js: Property callee of CallExpression expected node to be of a type ["Expression"] but instead got null
    at Object.validate (/Users/mgardner/default-package/node_modules/babel-types/lib/definitions/index.js:109:13)
    at Object.validate (/Users/mgardner/default-package/node_modules/babel-types/lib/index.js:505:9)
    at NodePath._replaceWith (/Users/mgardner/default-package/node_modules/babel-traverse/lib/path/replacement.js:176:7)
    at NodePath._remove (/Users/mgardner/default-package/node_modules/babel-traverse/lib/path/removal.js:58:10)
    at NodePath.remove (/Users/mgardner/default-package/node_modules/babel-traverse/lib/path/removal.js:30:8)
    at PluginPass.CallExpression (/Users/mgardner/default-package/node_modules/babel-plugin-transform-es2015-modules-amd/lib/index.js:42:12)
    at NodePath._call (/Users/mgardner/default-package/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/mgardner/default-package/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/mgardner/default-package/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/mgardner/default-package/node_modules/babel-traverse/lib/context.js:150:16)

The broccoli plugin was instantiated at:
    at Babel.Plugin (/Users/mgardner/default-package/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/Users/mgardner/default-package/node_modules/broccoli-persistent-filter/index.js:62:10)
    at new Babel (/Users/mgardner/default-package/node_modules/broccoli-babel-transpiler/index.js:35:10)
    at Babel (/Users/mgardner/default-package/node_modules/broccoli-babel-transpiler/index.js:30:12)
    at Class.transpileTree (/Users/mgardner/default-package/node_modules/ember-cli-babel/index.js:38:48)
    at Object.toTree (/Users/mgardner/default-package/node_modules/ember-cli-babel/index.js:45:30)
    at /Users/mgardner/default-package/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/Users/mgardner/default-package/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessJs (/Users/mgardner/default-package/node_modules/ember-cli-preprocess-registry/preprocessors.js:171:10)
```

**Comment by allthesignals** [comment]
Alright, for some reason, `ember install ember-semantic-ui` is creating a `bower_components` folder inside `/app`. My SublimeText is configured to ignore and not watch any /bower_components folder, so I was not seeing it (only in version control).
