### ISSUE TITLE
TypeError: Cannot read property 'set' of undefined

### ISSUE THREAD

**Issue by ahawad** [Semantic-Org/Semantic-UI-Ember#40]
When I served the production version of my application issuing the openModal action led to the following error:
`TypeError: Cannot read property 'set' of undefined
    at exports.default.Ember.default.Mixin.create.actions.openModal (http://localhost:4200/assets/vendor-f3c503d5f352702ca4f036b6c6b3aea8.js:72591:21)
    at Object.triggerEvent (http://localhost:4200/assets/vendor-f3c503d5f352702ca4f036b6c6b3aea8.js:33812:36)
    at trigger (http://localhost:4200/assets/vendor-f3c503d5f352702ca4f036b6c6b3aea8.js:53760:16)
    at Object.Router.trigger (http://localhost:4200/assets/vendor-f3c503d5f352702ca4f036b6c6b3aea8.js:52484:9)
    at EmberObject.default.extend.send (http://localhost:4200/assets/vendor-f3c503d5f352702ca4f036b6c6b3aea8.js:33310:40)
    at mixin.Mixin.create.send (http://localhost:4200/assets/vendor-f3c503d5f352702ca4f036b6c6b3aea8.js:36968:29)
    at confirm (http://localhost:4200/assets/my-blog-aa713d0569e9c7329f64b9279bff4503.js:118:14)
    at mixin.Mixin.create.send (http://localhost:4200/assets/vendor-f3c503d5f352702ca4f036b6c6b3aea8.js:36961:54)
    at runRegisteredAction (http://localhost:4200/assets/vendor-f3c503d5f352702ca4f036b6c6b3aea8.js:28506:25)
    at Object.Backburner.run (http://localhost:4200/assets/vendor-f3c503d5f352702ca4f036b6c6b3aea8.js:10778:27)`

Any idea what I am doing wrong?

**Comment by ahawad** [comment]
I figured it out. In case someone else runs into this, it seems that there is an error is introduced in the Ember.generate.controller call in the try/catch block of the mixin. I fixed it by generating an empty controller for the modal's template.
